// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk5GoYiPLp-AF4ZBCcDjL2RRVvA82u0NY',
    appId: '1:682310068054:android:ea21ee1e61d74fcb6258f7',
    messagingSenderId: '682310068054',
    projectId: 'partyminimap-9ea36',
    databaseURL: 'https://partyminimap-9ea36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'partyminimap-9ea36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlDLRP_hQiU3SAoy0vhTgV_UnfGQ6m9o',
    appId: '1:682310068054:ios:b593b54459b1ef546258f7',
    messagingSenderId: '682310068054',
    projectId: 'partyminimap-9ea36',
    databaseURL: 'https://partyminimap-9ea36-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'partyminimap-9ea36.firebasestorage.app',
    iosClientId: '682310068054-192miipjeo23uv41kgspg08kffaluu74.apps.googleusercontent.com',
    iosBundleId: 'com.example.partyMinimap',
  );

}